version: '3.8'

services:
  cities-client:
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run start
    image: cities-client:1
    container_name: cl_cities
    ports:
      - "8084:3000"
    links:
      - app_cities
    depends_on:
      - app_cities
    volumes:
      - ./:/cl_cities
      - /cl_cities/node_modules
    environment:
      - API_BASE_URL=app_cities:8083/